In [1]:
import numpy as np

def max_min_s(X):
    # the two-step process as described above
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])
print(max_min_s(X_train))

[[0. 0.]
 [1. 1.]]


In [ ]:
def try_it_myself(X):
    
    
    
X_train2 = np.array([[1000.0, 2.0], [1500.0, 3.0]])
print(try_it_myself(X_train2))

In [4]:
# Let's use the Sklearn preprocessing package to do the same thing as our above function:

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


In [2]:
def standard_s(X):
    return (X - X.mean(axis=0)) /X.std(axis=0) 

print(standard_s(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [6]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]
